version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build:
      context: .
      target: dev
    command: python manage.py runserver 0.0.0.0:8005
    volumes:
      - .:/code
    ports:
      - "8005:8005"
    depends_on:
      - db
    environment:
      - EXTERNAL_API_URL=${EXTERNAL_API_URL}
      - API_KEY=${API_KEY}
